#!/usr/bin/env python3
"""Generate the deprecated ``nexa*`` aliases for FluxaWay dist artifacts.

``fluxaway*`` is the canonical public surface. The small aliases generated by
this script keeps existing Nexa URLs working during the compatibility window
without maintaining two independent copies of the framework.

Usage:
  python3 scripts/sync_legacy_aliases.py
  python3 scripts/sync_legacy_aliases.py --check
"""

from __future__ import annotations

import sys
from pathlib import Path


DIST = Path(__file__).resolve().parent.parent / "dist"
CANONICAL_PREFIX = "fluxaway"
LEGACY_PREFIX = "nexa"


def alias_content(canonical: Path) -> str:
    canonical_name = canonical.name
    suffix = canonical_name.removeprefix(CANONICAL_PREFIX)
    target = f"./{canonical_name}"

    if canonical_name in {"fluxaway-hmr.js", "fluxaway-hmr.min.js"}:
        return (
            "/*! Nexa compatibility alias — use "
            f"{canonical_name}. */\n"
            "(() => {\n"
            '  const current = document.currentScript;\n'
            '  const script = document.createElement("script");\n'
            f'  script.src = new URL("{target}", current?.src ?? '
            'document.baseURI).href;\n'
            "  document.head.append(script);\n"
            "})();\n"
        )

    if suffix.endswith(".d.ts"):
        runtime_name = canonical_name.removesuffix(".d.ts") + ".js"
        return (
            "/** @deprecated Import from "
            f'"./{runtime_name}" instead. */\n'
            f'export * from "./{runtime_name}";\n'
        )

    if suffix.endswith(".js"):
        return (
            "/*! Nexa compatibility alias — use "
            f"{canonical_name}. */\n"
            f'export * from "{target}";\n'
        )

    if suffix.endswith(".css"):
        return (
            "/*! Nexa compatibility alias — use "
            f"{canonical_name}. */\n"
            f'@import url("{target}");\n'
        )

    raise ValueError(f"unsupported canonical artifact: {canonical_name}")


def expected_aliases() -> dict[Path, str]:
    aliases = {}
    for canonical in sorted(DIST.glob(f"{CANONICAL_PREFIX}*")):
        if not canonical.is_file():
            continue
        legacy_name = LEGACY_PREFIX + canonical.name.removeprefix(CANONICAL_PREFIX)
        aliases[DIST / legacy_name] = alias_content(canonical)
    return aliases


def main(argv: list[str]) -> int:
    check = "--check" in argv
    aliases = expected_aliases()

    if check:
        stale = [
            path.name
            for path, content in aliases.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print(
                "Legacy aliases are stale "
                "(run: python3 scripts/sync_legacy_aliases.py):"
            )
            for name in stale:
                print(f"  - {name}")
            return 1
        print(f"All {len(aliases)} Nexa compatibility aliases are up to date.")
        return 0

    for path, content in aliases.items():
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.name}")
    print(f"Generated {len(aliases)} Nexa compatibility aliases.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
